# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "37c0d734-7f0d-4029-bdf6-08a1d3b31f24"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "e44ff351c80bd5e137a43c01d98efbb97d0d1337",
    build_secret: "37763f388ec264e8df8999beffb569965433c2455a015e8eb7044af51dd8d862"
  )
end
